/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Form;

import Koneksi.Database;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Setting extends javax.swing.JFrame {

    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
        showUsername();
    }

    public void showUsername(){
        java.sql.Connection conn= new Database().connect();        
        try{
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery("select *from session");
            while(rs.next()){
                lblUser.setText(rs.getString("username"));
            }
        }catch(Exception e){
        JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void update(){
    
        if (!jPasswordField_new.getText().equals(jPasswordField_conf.getText())) {
         JOptionPane.showMessageDialog(null,"Confirmation Not Match");
    }
           
    else    {
     java.sql.Connection conn = new Database().connect();
        try{
            
            java.sql.PreparedStatement stmt= conn.prepareStatement("update login set password =? , confirm=? where username =?");
            
            try{  
               
                stmt.setString(1,jPasswordField_new.getText());
                stmt.setString(2,jPasswordField_conf.getText());
                stmt.setString(3,lblUser.getText());
                stmt.executeUpdate();
                dispose();
            
            }catch(SQLException ex){
             
            }
            
        }catch(Exception e){
         
         
        }   
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField_old = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField_new = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPasswordField_conf = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblUser = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("INPUT OLD PASSWORD");

        jPasswordField_old.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_old.setText("jPasswordField1");
        jPasswordField_old.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_oldMouseClicked(evt);
            }
        });
        jPasswordField_old.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_oldKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_oldKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("INPUT NEW PASSWORD");

        jPasswordField_new.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_new.setText("jPasswordField1");
        jPasswordField_new.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_newMouseClicked(evt);
            }
        });
        jPasswordField_new.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_newKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_newKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("CONFIRM NEW PASSWORD");

        jPasswordField_conf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPasswordField_conf.setText("jPasswordField1");
        jPasswordField_conf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField_confMouseClicked(evt);
            }
        });
        jPasswordField_conf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField_confKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jPasswordField_confKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("CONFIRM");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("USERNAME");

        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setText("-");

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setText("CANCEL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(49, 49, 49)
                        .addComponent(jPasswordField_new))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordField_conf, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jPasswordField_old))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_old, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jPasswordField_new, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField_conf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPasswordField_oldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_oldMouseClicked
        // TODO add your handling code here:
        jPasswordField_old.setText("");
    }//GEN-LAST:event_jPasswordField_oldMouseClicked

    private void jPasswordField_oldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_oldKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jPasswordField_new.requestFocus();
            jPasswordField_new.setText("");
            jPasswordField_new.setEnabled(true);
            jPasswordField_old.setEnabled(false);
        }

    }//GEN-LAST:event_jPasswordField_oldKeyPressed

    private void jPasswordField_oldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_oldKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();
        if(jPasswordField_old.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_jPasswordField_oldKeyTyped

    private void jPasswordField_newMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_newMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_newMouseClicked

    private void jPasswordField_newKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_newKeyPressed
        // TODO add your handling code here:
        if (jPasswordField_new.getText().equals("")) {
            jPasswordField_new.requestFocus();
        }

        else if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            if(jPasswordField_new.getText().length() <6){
                JOptionPane.showMessageDialog(null,"PASSWORD MINIMAL 6");
                jPasswordField_new.requestFocus();

            }
            else {

                jPasswordField_conf.requestFocus();
                jPasswordField_conf.setText("");
                jPasswordField_conf.setEnabled(true);
                jPasswordField_new.setEnabled(false);

            }
        }

    }//GEN-LAST:event_jPasswordField_newKeyPressed

    private void jPasswordField_newKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_newKeyTyped
        // TODO add your handling code here:
        char karakter = evt.getKeyChar();

        if(jPasswordField_new.getText().length()==0 && karakter == KeyEvent.VK_SPACE)
        {
            getToolkit().beep();
            evt.consume();

        }
    }//GEN-LAST:event_jPasswordField_newKeyTyped

    private void jPasswordField_confMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField_confMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_confMouseClicked

    private void jPasswordField_confKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_confKeyPressed
        // TODO add your handling code here:

        if (evt.getKeyCode()== KeyEvent.VK_ENTER)
        {
            jPasswordField_conf.setEnabled(false);
        }
    }//GEN-LAST:event_jPasswordField_confKeyPressed

    private void jPasswordField_confKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField_confKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField_confKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        java.sql.Connection conn = new Database().connect();

        try {
            java.sql.Statement stmt = conn.createStatement();
            String SQL = " select *from login ";
            java.sql.ResultSet res= stmt.executeQuery(SQL);

            while(res.next()){
                if (jPasswordField_old.getText().equals(res.getString("password"))){
                    update();
                }
                
            }
        }catch (SQLException e){

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Setting.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Setting().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField_conf;
    private javax.swing.JPasswordField jPasswordField_new;
    private javax.swing.JPasswordField jPasswordField_old;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
